name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: test123
          MYSQL_DATABASE: animethemes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Import database dump
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          sudo /etc/init.d/mysql start
          curl https://github.com/AnimeThemes/animethemes-db-dump/raw/wiki/mysql/animethemes-db-dump-create-tables.sql | mysql --user=root --password=test123 --host=127.0.0.1 --port="$PORT" animethemes

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Gatsby pages
        run: npm run build-with-paths
        env:
          GATSBY_PATH_PREFIX: /animethemes-web
          GATSBY_CI: true
          SOURCE_PLUGIN: DB
          DB_USER: root
          DB_PASSWORD: test123
          DB_PORT: ${{ job.services.mariadb.ports[3306] }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
